# The API endpoint of the bot
#api_endpoint = "http://127.0.0.1:8000"

# Embed colors
[color]
server_online_race = "#3eb3f7"
server_online_battle = "#f7283c"
server_online_custom = "#42ed53"
server_offline = "#1b1b27"

[messages]
gathered = [
  "A dark, forboding feeling overtakes you. You know this Mogi's conclusion, even in its infancy.",
  "<@&1336926299221917778> why you trying not to laugh",
  "<:zazakiller:1437184417540997241>",
  "<:trolley:1384661421358317735>",
  "Night 6",
  "oh no bro",
  "backing quads tight gl",
  "Do you know who else canned up for a mogi in the Dr. Robotnik's Ring Racers Lounge?",
  "\"Daniel please stop canning\"",
  "Mario has logged in.",
  "time to farm!",
  "we might be cooked.",
  "the plan is simple",
  "the plan is rather complex in nature",
  "so two bronzes walked into tier wall",
  "why are they moving",
  "50 pons to gutbuster",
  "Gutbuster has sent deathlink",
  "it's so chill",
  "I believe <@230853305234882560> is going to enjoy this 👀",
  "gah damn",
  "who wants to can for 2.3 derby?",
  "\"can down\" - gunla 2025",
  "guess what",
  "chicken butt",
  "You acknowledge the possibility of losing even though you pulled invincibility.",
  "i... need... amps!",
  "You didn't have to chain...",
  "its time to rage chain.",
  "Mogi Lounge's tier-s is in Bah's the-arena in Doctor Robotniks Ring Racers",
  "GIVE IT UP FOR MOGI 15 OF NONSTOP TEAMS FORMATS!",
  "Initiating 1 hour of Spring Yard Zone legalization discorse.",
  "Legalize Pico Park 1 <:trolley:1384661421358317735>",
  "if this message gets 20 reacts in <#1289423524234002524> I will play all of the current season with 1, 9 stats",
  "unban motobug motorway you cowards",
  "What is that one map that uhhh tha- that is very blue and has water in it and....*swallows*....and red trick panels and is very fast a- and is and I think is very cool and yeah",
  "idk.",
  "Have a nice day! Bow wow!",
  "would you rather have 1 mobium or 2 mobiums",
  "GAWD DAMN",
  "Maybe someday I'll publish a map pack...",
  "I'm Earling It.",
  "\"Shit yourself\" -Various",
  "Goobey",
  "We still play this map for MMR",
  "Battle games I wanna whip, I whip 'em all I wanna whip all day I'm not inting, I'm not inting You shoulda learned to drive away Yes I whip them all, so I whip them all I wanna whip all day I'm not inting, I'm not inting You shoulda seen my last battle games!",
  "Class B is downplayed because they don't want you to know how fucking easy it is",
  "mighty eagle pissing gif",
  "just be patient",
  "lgomo was co-opted from Lemin I saw your crimes log man at least pay him royalties",
  "deadlock invite pls",
  "mergasofine",
  "hey, its me, its verity. ask me anything",
  "67",
  "1238 🔒",
  "-50mmr penalty if %ru isn't Bomb this mogi <:trolley:1384661421358317735>",
  "CODE TRINGLE",
  "learning to hate ring racers",
  "can't wait for the midbus vod",
  "I'm popping ult...",
  "Hey Shirt, check this one out.",
  "@volrez we need you",
  "is ieatpoop96 in this lobby",
  "1/8 for derby",
  "reyalp is washed btw",
  "1-2 ffa 3-4 2v2 5-6 4v4",
  "galactice pen at :09",
  "kirby air riders lobby: WJA34S",
  "Cookie has joined the mogi -- 32 players",
  "/d",
  "gentlemans to carnival night",
  "1/4 for mario party star rush",
  "tag ball color vomit",
  "mercy 1/4",
  "Nice 7 8",
  "i wonder who's running top 2",
  "this lobby is so fat -hope",
  "this track is wider than daniel's mom",
  "WIL RESPAWN? HOW DO YOU RESPAWN ON ROBOTNIK FUCKING COASTER",
  "midbus I'm on paragraph 1 rn",
  "WHAT PLAYER DOES DANIEL NOT DO WELL WITH? IF YOU HAVE EARS AND A LIVER,",
  "Bah, who cares. I wanted to play a mogi before the Dusk falls, but that seems to be impossible. Nothing but Pure heartbreak, I guess I'll just Doodle for the time being. Need some Icethatscool and some Phil's Pills to clear this headache.",
  "Regigigas can't get it going!",
  "Try \"quit smoking\" in console!",
  "YOU'RE LITERALLY INTING ME!",
  "flameshot fred back at it again",
  "rectangle ✅ ✅ ✅ ✅",
  "What is THIS nightmare blunt rotation ass map pool??",
  "im kirking it",
  "its happening",
]
